### ISSUE TITLE
CoCT stage 4 overnight and stage 3 during the day

### ISSUE THREAD

**Issue by extremeshok** [chrismailer/loadshedding#1]
The calendar appears to be inaccurate due to how the CoCT stages increases back to eskom stages during the night.

stage 3 from 06:00 to 22:00
stage 4 from 22:00 to 22:00

**Comment by chrismailer** [comment]
Thanks, I'd missed that schedule update. Should be correct now. Just a warning, if you're using google calendar it can take up to 12hrs to update which is quite annoying with these quick schedule changes.
